config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions'
  }
  resources :tasks
  root 'tasks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :assigner_id, :assignee_id, :due_date)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.haml
= form_with(model: task, local: true) do |form|
  - if task.errors.any?
    #error_explanation
      %h2
        = pluralize(task.errors.count, "error")
        prohibited this task from being saved:
      %ul
        - task.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :title
    = form.text_field :title, id: :task_title
  .field
    = form.label :description
    = form.text_area :description, id: :task_description
  .field
    = form.label :assigner_id
    = form.number_field :assigner_id, id: :task_assigner_id
  .field
    = form.label :assignee_id
    = form.text_field :assignee_id, id: :task_assignee_id
  .field
    = form.label :due_date
    = form.datetime_select :due_date, id: :task_due_date
  .actions
    = form.submit

app/views/tasks/edit.html.haml
%h1 Editing Task
= render 'form', task: @task
= link_to 'Show', @task
|
= link_to 'Back', tasks_path

app/views/tasks/index.html.haml
.tasks-container
  %ul
    %li
      .row
        .col-md-10
          .task-index 1
          .task-content
            Lorem ipsum dolor sit amet, consectetur adipisicing elit.
            %br
            .assigned-to 
              %span.assigned-title Assigned to
              Muhammed Anees
              %span.assigned-title on 
              12/11/2016
        .col-md-2
          .task-actions
            .task-action
              %a.delete-task
                %i.icon-trash

app/views/tasks/new.html.haml
%h1 New Task
= render 'form', task: @task
= link_to 'Back', tasks_path

app/views/tasks/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @task.title
%p
  %strong Description:
  = @task.description
%p
  %strong Assigner:
  = @task.assigner_id
%p
  %strong Assignee:
  = @task.assignee_id
%p
  %strong Due date:
  = @task.due_date
= link_to 'Edit', edit_task_path(@task)
|
= link_to 'Back', tasks_path